config/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import include, path

from django.views.generic.base import RedirectView, TemplateView

from sso.admin.views import admin_login_view
from sso.healthcheck.views import HealthCheckView
from . import api_urls

app_name = "staff_sso"

admin.site.site_header = "Staff-SSO Admin Section"
admin.site.site_title = ""
admin.site.index_title = ""

urlpatterns = [
    path("", RedirectView.as_view(pattern_name=settings.LOGIN_URL)),
    path("admin/login/", admin_login_view),
    path("admin/", admin.site.urls),
    path("admin/", include("sso.user.admin_urls")),
    path("saml2/", include("sso.samlauth.urls")),
    path("idp/", include("djangosaml2idp.urls", namespace="djangosaml2idp")),
    path("idp/", include("sso.samlidp.urls", namespace="samlidp")),
    # override authorisation and token introspection DOT views
    path("o/", include("sso.oauth2.urls", namespace="oauth2")),
    path("o/", include(("oauth2_provider.urls", "oauth2_provider"), namespace="oauth2_provider")),
    path("api/v1/", include((api_urls, "api"), namespace="api-v1")),
    path("", include(("sso.contact.urls", "sso_contact"), namespace="contact")),
    path("email/", include(("sso.emailauth.urls", "sso_emailauth"), namespace="emailauth")),
    path("", include(("sso.localauth.urls", "sso_localauth"), namespace="localauth")),
    path("check/", HealthCheckView.as_view(), name="healthcheck"),
    path(
        "privacy-policy/",
        TemplateView.as_view(template_name="sso/privacy-policy.html"),
        name="privacy_policy",
    ),
]

sso/core/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path("activity-stream/", views.activity_stream, name="activity-stream"),
]

sso/oauth2/urls.py
from django.urls import path

from .views import CustomAuthorizationView, CustomIntrospectTokenView

app_name = "staff_sso_oauth2"

urlpatterns = [
    path("authorize/", CustomAuthorizationView.as_view(), name="authorize"),
    path("introspect/", CustomIntrospectTokenView.as_view(), name="introspect"),
]

sso/user/urls.py
from django.urls import path

from .views import UserIntrospectViewSet, UserListViewSet, UserRetrieveViewSet

urlpatterns = [
    path(
        "me/",
        UserRetrieveViewSet.as_view(
            {
                "get": "retrieve",
                "patch": "partial_update",
            }
        ),
        name="me",
    ),
    path("introspect/", UserIntrospectViewSet.as_view({"get": "retrieve"}), name="user-introspect"),
    path("search/", UserListViewSet.as_view({"get": "list"}), name="user-search"),
]

sso/contact/forms.py
from django import forms
from django.utils.translation import gettext_lazy as _


class RequestAccessForm(forms.Form):
    full_name = forms.RegexField(
        label=_("Full name"),
        max_length=200,
        regex=r"^[A-Za-z\.\- ]*$",
        widget=forms.TextInput(attrs={"class": "form-control"}),
        error_messages={
            "required": "Provide your full name",
            "invalid": "Provide a valid full name without punctuation",
        },
    )
    team = forms.RegexField(
        label=_("Team"),
        regex=r"^[A-Za-z0-9\&\.\-\(\) ]*$",
        widget=forms.TextInput(attrs={"class": "form-control"}),
        error_messages={
            "required": "Provide your team name",
            "invalid": "Provide a valid team name without punctuation",
        },
    )

sso/admin/views.py
from django.conf import settings
from django.core.exceptions import PermissionDenied
from django.shortcuts import redirect
from django.urls import reverse


def admin_login_view(request):
    """A replacement admin login view that will direct the user through the SSO
    authentication flow."""

    next_url = request.GET.get("next", reverse("admin:index"))

    if request.user.is_authenticated:
        if not request.user.is_staff:
            raise PermissionDenied

        return redirect(next_url)

    return redirect("%s?next=%s" % (reverse(settings.LOGIN_URL), next_url))

sso/contact/views.py
from django.conf import settings
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views.generic.edit import FormView

from zenpy import Zenpy
from zenpy.lib.api_objects import CustomField, Ticket, User as ZendeskUser

from sso.oauth2.views import LAST_FAILED_APPLICATION_SESSION_KEY
from .forms import RequestAccessForm


class AccessDeniedView(FormView):
    template_name = "sso/access-denied.html"
    form_class = RequestAccessForm
    success_url = reverse_lazy("contact:success")

    def form_valid(self, form):

        ticket_id = self.create_zendesk_ticket(form.cleaned_data)

        return render(
            self.request, "sso/request-access-success.html", dict(zendesk_ticket_id=ticket_id)
        )

    def get_zendesk_client(self):
        # Zenpy will let the connection timeout after 5s and will retry 3 times
        return Zenpy(timeout=5, **settings.ZENPY_CREDENTIALS)

    def create_zendesk_ticket(self, cleaned_data):

        email = self.request.user.email
        application = self.request.session.get(LAST_FAILED_APPLICATION_SESSION_KEY, "Unspecified")

        zendesk_user = ZendeskUser(name=cleaned_data["full_name"], email=email)

        description = (
            "Name: {full_name}\n" "Team: {team}\n" "Email: {email}\n" "Application: {application}\n"
        ).format(email=email, application=application, **cleaned_data)
        ticket = Ticket(
            subject=settings.ZENDESK_TICKET_SUBJECT,
            description=description,
            requester=zendesk_user,
            custom_fields=[CustomField(id="31281329", value="auth_broker")],
        )
        response = self.get_zendesk_client().tickets.create(ticket)
        return response.ticket.id

sso/core/views.py
import datetime
import hmac
import uuid

from django.conf import settings
from django.contrib.auth import get_user_model
from django.http import JsonResponse
from django.urls import reverse
from django.views.decorators.csrf import csrf_exempt
from django.views.decorators.http import require_GET
from hawkserver import authenticate_hawk_header

from sso.oauth2.models import Application as OAuthApplication


@require_GET
@csrf_exempt
def activity_stream(request):
    def forbidden():
        return JsonResponse(
            data={},
            status=403,
        )

    ############################################
    ## Ensure not accessed via public networking

    via_public_internet = "x-forwarded-for" in request.headers
    if via_public_internet:
        return forbidden()

    ###########################
    ## Ensure signed with Hawk

    def lookup_credentials(passed_id):
        user = {
            "id": settings.ACTIVITY_STREAM_HAWK_ID,
            "key": settings.ACTIVITY_STREAM_HAWK_SECRET,
        }
        return user if hmac.compare_digest(passed_id, user["id"]) else None

    def seen_nonce(nonce, id):
        # No replay attack prevention since no shared cache between instances,
        # but we're ok with that for
        return False

    try:
        request.headers["authorization"]
    except KeyError:
        return forbidden()

    # This is brittle to not running in PaaS or not via private networking
    host, port = request.META["HTTP_HOST"].split(":")

    max_skew_seconds = 15
    error_message, credentials = authenticate_hawk_header(
        lookup_credentials,
        seen_nonce,
        max_skew_seconds,
        request.headers["authorization"],
        request.method,
        host,
        port,
        request.get_full_path(),
        request.headers.get("content-type", ""),
        request.body,
    )
    if error_message is not None:
        return forbidden()

    #############
    ## Get cursor

    after_ts_str, after_user_id_str = request.GET.get(
        "cursor", "0.0_00000000-0000-4000-0000-000000000000"
    ).split("_")
    after_ts = datetime.datetime.fromtimestamp(float(after_ts_str))
    after_user_id = uuid.UUID(after_user_id_str)

    ##########################################################
    ## Fetch activities after cursor (i.e. user modifications)

    # `STATEMENT_TIMESTAMP`: it is often more typical to use CURRENT_TIMESTAMP,
    # however, CURRENT_TIMESTAMP is the time of the start of the current
    # transaction, and pytest tests are run in a transaction, so
    # CURRENT_TIMESTAMP does not progress
    #
    # `- INTERVAL 1 second`: `last_modified` is not strictly monotonically
    # increasing due to overlapping transactions committed in a non-guarenteed
    # order. It's technically an eventually consistent situation, so updates
    # can be missed if serveral are close together. We mitigate this risk by
    # adding a delay before activities appear in the stream.

    per_page = 50
    User = get_user_model()
    users = list(
        User.objects.only(
            "user_id",
            "email_user_id",
            "last_modified",
            "last_accessed",
            "is_active",
            "first_name",
            "last_name",
            "email",
            "contact_email",
            "date_joined",
        )
        .prefetch_related(
            "emails",
            "permitted_applications",
            "access_profiles__oauth2_applications",
            "access_profiles__saml2_applications",
        )
        .extra(
            where=[
                "(last_modified, user_id) > (%s, %s)",
                "last_modified < STATEMENT_TIMESTAMP() - INTERVAL '1 second'",
            ],
            params=(after_ts, after_user_id),
        )
        .order_by("last_modified", "user_id")[:per_page]
    )

    ################################################################
    ## Convert to activities, with link to next page if at least one

    def next_url(after_ts, after_user_id):
        return request.build_absolute_uri(
            reverse("api-v1:core:activity-stream")
        ) + "?cursor={}_{}".format(str(after_ts.timestamp()), str(after_user_id))

    def without_duplicates(seq):
        seen = set()
        return [x for x in seq if not (x in seen or seen.add(x))]

    default_access_apps = OAuthApplication.get_default_access_applications()

    page = {
        "@context": [
            "https://www.w3.org/ns/activitystreams",
            {"dit": "https://www.trade.gov.uk/ns/activitystreams/v1"},
        ],
        "type": "Collection",
        "orderedItems": [
            {
                "id": f"dit:StaffSSO:User:{user.user_id}:Update",
                "published": user.last_modified,
                "object": {
                    "id": f"dit:StaffSSO:User:{user.user_id}",
                    "type": "dit:StaffSSO:User",
                    "name": user.get_full_name(),
                    "dit:StaffSSO:User:userId": user.user_id,
                    "dit:StaffSSO:User:emailUserId": user.email_user_id,
                    "dit:StaffSSO:User:contactEmailAddress": user.contact_email
                    if user.contact_email
                    else None,
                    "dit:StaffSSO:User:joined": user.date_joined,
                    "dit:StaffSSO:User:lastAccessed": user.last_accessed,
                    "dit:StaffSSO:User:permittedApplications": [
                        {
                            # name and url are both in the W3C Activity Streams 2.0 Vocab
                            "name": app["name"],
                            "url": app["url"],
                        }
                        for app in user.get_permitted_applications(
                            include_non_public=True,
                            get_default_access_allowed_apps=lambda: default_access_apps,
                        )
                    ],
                    "dit:StaffSSO:User:status": "active" if user.is_active else "inactive",
                    "dit:StaffSSO:User:becameInactiveOn": None
                    if user.is_active
                    else user.became_inactive_on,
                    "dit:firstName": user.first_name,
                    "dit:lastName": user.last_name,
                    "dit:emailAddress": without_duplicates(
                        [user.email] + sorted([email.email for email in user.emails.all()])
                    ),
                },
            }
            for user in users
        ],
        **({"next": next_url(users[-1].last_modified, users[-1].user_id)} if users else {}),
    }

    return JsonResponse(
        data=page,
        status=200,
    )

sso/emailauth/views.py
import datetime as dt

from django.conf import settings
from django.contrib.auth import get_user_model, login
from django.shortcuts import redirect, render
from django.views.generic import View
from django.views.generic.edit import FormView

from sso.core.logging import create_x_access_log

from .forms import EmailForm
from .models import EmailToken

try:
    from django.urls import reverse, reverse_lazy
except ImportError:
    from django.core.urlresolvers import reverse, reverse_lazy


class InvalidToken(Exception):
    pass


class EmailTokenView(FormView):
    form_class = EmailForm
    template_name = "emailauth/initiate.html"
    success_url = reverse_lazy("emailauth:email-auth-initiate-success")

    def get(self, request, *args, **kwargs):

        if request.user.is_authenticated:
            return redirect("saml2_logged_in")

        return super().get(request, *args, **kwargs)

    def form_valid(self, form):

        form.send_signin_email(self.request)

        response = super().form_valid(form)
        response.set_cookie(
            "sso_auth_email", form.email, expires=dt.datetime.today() + dt.timedelta(days=30)
        )

        return response

    def get_initial(self):

        initial = super().get_initial()

        email = self.request.COOKIES.get("sso_auth_email", None)

        if email:
            username, domain = email.split("@")
            domain = "@" + domain

            if domain in settings.EMAIL_TOKEN_DOMAIN_WHITELIST:
                initial["username"] = username
                initial["domain"] = domain

        return initial


class EmailAuthView(View):
    permanent = False
    query_string = True

    invalid_token_template_name = "emailauth/invalid-token.html"
    valid_token_template_name = "emailauth/signin.html"

    def get(self, request, *args, **kwargs):
        try:
            token_obj = self.get_token_object(kwargs["token"])
        except InvalidToken:
            return render(request, self.invalid_token_template_name)

        return render(request, self.valid_token_template_name, {"user": token_obj.get_user().email})

    def post(self, request, *args, **kwargs):
        try:
            token_obj = self.get_token_object(kwargs["token"])
        except InvalidToken:
            return render(request, self.invalid_token_template_name)

        user = token_obj.get_user()
        user.backend = "django.contrib.auth.backends.ModelBackend"

        login(self.request, user)

        token_obj.mark_used()

        create_x_access_log(request, 200, message="Email Token Auth", email=token_obj.email)
        get_user_model().objects.set_email_last_login_time(token_obj.email)

        return redirect(self.get_next_url())

    def get_token_object(self, token):
        try:
            token_obj = EmailToken.objects.get(token=token, used=False)
        except EmailToken.DoesNotExist:
            raise InvalidToken

        if token_obj.is_expired:
            raise InvalidToken

        return token_obj

    def get_next_url(self):
        next_url = self.request.GET.get("next", "").strip()

        if next_url:
            return next_url
        else:
            return reverse("saml2_logged_in")

sso/healthcheck/views.py
import time

from django.contrib.auth import get_user_model
from django.views.generic import TemplateView
from raven.contrib.django.raven_compat.models import client


class HealthCheckView(TemplateView):
    template_name = "sso/health-check.html"

    def _do_check(self):
        """Perform a basic DB test"""
        try:
            get_user_model().objects.exists()
            return True

        except Exception:
            client.captureException()
            return False

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        context["status"] = "OK" if self._do_check() else "FAIL"

        # nearest approximation of a response time
        context["response_time"] = time.time() - self.request.start_time

        return context

sso/localauth/views.py
from axes.decorators import axes_dispatch
from django.conf import settings
from django.contrib.auth import views
from django.shortcuts import Http404
from django.utils.decorators import method_decorator

from .models import DomainWhitelist


class FeatureFlaggedMixin:
    def dispatch(self, *args, **kwargs):
        if not getattr(settings, "LOCAL_AUTH_PAGE"):
            raise Http404()
        return super().dispatch(*args, **kwargs)


@method_decorator(axes_dispatch, name="dispatch")
class LoginView(FeatureFlaggedMixin, views.LoginView):
    pass


class LogoutView(views.LogoutView):
    def get_success_url_allowed_hosts(self):
        domains = list(DomainWhitelist.objects.all().values_list("domain", flat=True))
        return {self.request.get_host(), *domains}

    def get_next_page(self):
        next_page = super().get_next_page()

        # the stock get_next_page method redirects to request.path if the url is
        # deemed unsafe.  Instead we want to send the user to
        # settings.LOGOUT_REDIRECT_URL
        if next_page == self.request.path:
            next_page = settings.LOGOUT_REDIRECT_URL

        return next_page

sso/templates/sso/access-denied.html
{% extends 'sso/base.html' %}

{% block inner_content %}
<div class="container">
    <h1 class="heading-large">You do not have permission to access this service</h1>

    {% if request.user.is_authenticated %}
    <p>If you think you should have access or need to sign up to a DIT system then complete the form below:</p>

    <h2 class="heading-medium">Request Access</h2>
    <form method="post" action="{{ request.path }}" novalidate>
        {{ form.non_field_errors }}
        {% csrf_token %}
        <div class="form-group{% if form.full_name.errors %} form-group-error{% endif %}">
            <label class="form-label" for="id_full_name">Your name</label>
            {% if form.full_name.errors %}
            <span class="error-message">
                {{ form.full_name.errors }}
            </span>
            {% endif %}
            {{ form.full_name }}
        </div>
        <div class="form-group{% if form.team.errors %} form-group-error{% endif %}">
            <label class="form-label" for="id_team">Your team</label>
            {% if form.team.errors %}
            <span class="error-message">
                {{ form.team.errors }}
            </span>
            {% endif %}
            {{ form.team }}
        </div>
        <input class="button" type="submit" value="Submit">
    </form>
    {% endif %}
</div>
{% endblock %}

sso/templates/sso/base.html
{% extends 'govuk_template.html' %}
{% load static %}

{% block head %}
  {{ block.super }}
  <link href="{% static 'stylesheets/sso.css' %}" media="screen" rel="stylesheet" />
  {% if GOOGLE_TAG_CODE %}
<!-- Google Tag Manager -->
<script>(function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':
new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],
j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src=
'https://www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f);
})(window,document,'script','dataLayer','{{ GOOGLE_TAG_CODE }}');</script>
<!-- End Google Tag Manager -->
  {% endif %}
{% endblock %}

sso/templates/sso/enter-email.html
{% extends 'sso/base.html' %}

{% block inner_content %}
<div class="container">
    <h1 class="heading-large">Sign in to DIT internal services</h1>

    <form method="post">
        {% csrf_token %}

        <p>Enter your email address to be directed to the correct login page.</p>

        <p class="email-input">

            <label class="form-label" for="username">Email address</label>

            {{ form.email }}

            {% if form.email.errors %}
                <ul class="errorlist">
                  {% for error in form.email.errors %}
                    <li><span class="error-message">{{ error }}</span></li>
                  {% endfor %}
                </ul>
            {% endif %}
        </p>

        <p><input type="submit" class="button" value="Next step"></p>
    </form>

    <p><a href="{% url 'saml2_login' %}">Show all login options</a></p>

</div>
{% endblock %}

sso/templates/sso/health-check.html
<pingdom_http_custom_check>
    <status>{{ status }}</status>
    <response_time>{{ response_time }}</response_time>
</pingdom_http_custom_check>

sso/templates/sso/logged-in.html
{% extends 'sso/base.html' %}

{% block inner_content %}
<div class="container">
    <h1 class="heading-large">You have signed in to DIT internal services</h1>

    {% if applications %}
    <p>You can now use:</p>
    {% endif %}

    {% for application in applications %}
        <p>Go to <a href="{{ application.url | safe }}">{{ application.name }}</a></p>
    {% endfor %}

</div>
{% endblock %}

sso/templates/sso/logged-out.html
{% extends 'sso/base.html' %}

{% block inner_content %}
<div class="container">
    <h1 class="heading-large">You have been signed out</h1>
</div>
{% endblock %}

sso/templates/sso/login-initiate.html
{% extends 'sso/base.html' %}

{% block inner_content %}
<div class="container">
    <h1 class="heading-large">Sign in to DIT internal services</h1>

    <form method="post">
        {% csrf_token %}

        <p class="email-input">

            <label class="form-label" for="username">Enter your work email address</label>

            {{ form.email }}

            {% if form.email.errors %}
                <ul class="errorlist">
                  {% for error in form.email.errors %}
                    {% if error == '__unsupported_email__' %}
                        <li>
                            <span class="error-message">You can't use this email address to access DIT's internal services.
                            <a href="{% url 'saml2_login' %}{% if next %}?next={{ next }}{% endif %}">Sign in using a different method</a></span>
                        </li>
                    {% else %}
                        <li><span class="error-message">{{ error }}</span></li>
                    {% endif %}
                  {% endfor %}
                </ul>
            {% endif %}
        </p>
        <p>We will use your email address to identify your organisation. Each organisation has a different sign in service. We will direct you to the right service.</p>

        <p><input type="submit" class="button" value="Next step"></p>
    </form>

</div>
{% endblock %}

sso/templates/sso/privacy-policy.html
{% extends 'sso/base.html' %}

{% block inner_content %}
<div class="container">
    <h1 class="heading-large">Privacy Policy</h1>

    <p>Information provided whilst using this service, including personal information, may be published or disclosed in accordance with access to information regimes, primarily the Freedom of Information Act 2000 (FOIA) and UK Data Protection legislation. </p>

    <p>The Department for International Trade will process personal data supplied in this service in accordance with the Data Protection Act (DPA). The information you provide will be processed on a lawful basis in Single Sign-On (SSO) to enable DIT to perform a task in the public interest or to fulfil an official function, and the task or function has a clear basis in law and/or the processing is necessary for a contract DIT have with an individual and/or the individual has given consent for the processing of their personal data for a specific task.</p>

    <p>This information will be shared within the department and with selected third parties for purposes connected with DIT performing a task in the public interest or to fulfil an official function and the task or function has a clear basis in law, including:
        to manage access for all DIT users including staff, International Trade Advisors, Local Enterprise Partners, Devolved Administrations, contracted individuals and agencies and Investment Support Service Team to DIT Digital services such as Data Hub and Digital Workspace</p>

    <p>Third parties with whom data will be shared are the following identity providers:
        <ul>
            <li>Core</li>
            <li>Google</li>
            <li>Okta</li>
            <li>Microsoft</li>
        </ul>
    </p>

    <p>Aggregated analysis of responses may also be shared with the Information Commissioner’s Office (ICO) the Government Internal Audit Agency (GIAA) and the National Audit Office (NAO).</p>

    <p>Consent will be sought in accordance with the DPA should there be a requirement to share information with any other third parties outside of those listed above. If you want the information you provide to be treated confidentially, please be aware that, in accordance with the FOIA, public authorities are required to comply with a statutory code of practice which deals, amongst other things, with obligations of confidence. In view of this, it would be helpful if you could explain to us why you wish that information to be treated confidentially. If we receive a request for disclosure of that information, we will take full account of your explanation, but we cannot give an assurance that confidentiality can be maintained in all circumstances.</p>
</div>
{% endblock %}

sso/templates/sso/request-access-success.html
{% extends 'sso/base.html' %}

{% block inner_content %}
<div class="container">
    <h1 class="heading-large">Request submitted</h1>

    <p>Your request to access this service has been submitted.</p>

    <p>Your reference number for this request is <span class="strong bold">{{ zendesk_ticket_id }}</span></p>

    <p>Our team aim to respond to these requests within 3 working days.</p>

    <p>Should you require urgent support, please contact <a href="mailto:login.support@uktrade.zendesk.com">login.support@uktrade.zendesk.com</a>.</p>
</div>
{% endblock %}